version: "3.9"
services:
  supernode-1:
    image: flwr/supernode:${FLWR_VERSION:-1.23.0}
    command:
      - --insecure
      - --superlink
      - ${SERVER_IP:-host.docker.internal}:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=0 num-partitions=6"
    ports:
      - "9094:9094"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  superexec-clientapp-1:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/superexec:${FLWR_VERSION:-1.23.0}


        RUN pip install --no-cache-dir prometheus-client
        RUN pip install --no-cache-dir psutil


        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .
        ENTRYPOINT ["flower-superexec"]
    ports:
      - "8000:8000"          # ← Prometheus metrics for this client

    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-1:9094
    depends_on:
      - supernode-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./quickstart-sklearn-tabular/Data:/app/Data
      - ./quickstart-sklearn-tabular/Done:/app/Done

