[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sklearnexample"
version = "1.0.0"
description = "Federated Learning with scikit-learn and Flower (Quickstart Example)"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.22.0",
    "flwr-datasets[vision]>=0.5.0",
    "scikit-learn>=1.6.1",
    "torch>=2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "sklearnexample.server_app:app"
clientapp = "sklearnexample.client_app:app"

[tool.flwr.app.config]
penalty = "l2"
num-server-rounds = 3
min-available-clients = 1


[tool.flwr.federations.remote-deployment]
address = "localhost:9093"
insecure = true


[tool.flwr.client]
client_id = "client2"
data_path = "data/client2_data.csv"  # Path inside container
superlink = "superlink:9092"
